export const browserCoreExamples = [
  "webbot browser status",
  "webbot browser start",
  "webbot browser stop",
  "webbot browser tabs",
  "webbot browser open https://example.com",
  "webbot browser focus abcd1234",
  "webbot browser close abcd1234",
  "webbot browser screenshot",
  "webbot browser screenshot --full-page",
  "webbot browser screenshot --ref 12",
  "webbot browser snapshot",
  "webbot browser snapshot --format aria --limit 200",
  "webbot browser snapshot --efficient",
  "webbot browser snapshot --labels",
];

export const browserActionExamples = [
  "webbot browser navigate https://example.com",
  "webbot browser resize 1280 720",
  "webbot browser click 12 --double",
  'webbot browser type 23 "hello" --submit',
  "webbot browser press Enter",
  "webbot browser hover 44",
  "webbot browser drag 10 11",
  "webbot browser select 9 OptionA OptionB",
  "webbot browser upload /tmp/file.pdf",
  'webbot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "webbot browser dialog --accept",
  'webbot browser wait --text "Done"',
  "webbot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "webbot browser console --level error",
  "webbot browser pdf",
];
